/**
 * @file config_manager.h
 * @brief JSON Schema-Driven Configuration Management API
 * 
 * This module provides a simple key-value configuration system with:
 * - JSON schema as single source of truth (config_schema.json)
 * - Direct NVS key-value storage (no enums, no metadata tables)
 * - Type-safe API functions (string, int32, int16, bool)
 * - Build-time factory defaults generation (no runtime JSON parsing)
 * - Web integration: schema embedded for browser UI generation
 * 
 * ARCHITECTURE:
 * Config manager is a thin NVS wrapper with no validation logic.
 * Browser performs validation using JSON schema constraints.
 * 
 * USAGE:
 * 1. Define parameters in config_schema.json
 * 2. Build system generates config_factory_generated.c
 * 3. Application calls config_get_xxx("key"), config_set_xxx("key", value)
 * 4. Web UI fetches /config_schema.json and generates forms dynamically
 * 
 * MEMORY EFFICIENCY:
 * No runtime caches - direct NVS access on every get/set.
 * Trades CPU cycles for zero RAM overhead.
 * 
 * ERROR HANDLING:
 * All functions return esp_err_t for ESP-IDF error handling patterns.
 * 
 * @author ESP32 Template Project
 * @date 2025
 * @version 3.0 (JSON-based)
 * 
 * Requirements Traceability:
 * - REQ_CFG_JSON_1: JSON Schema as Source of Truth
 * - REQ_CFG_JSON_6: Key-Based NVS Storage
 * - REQ_CFG_JSON_7: Type-Safe Configuration API
 * - REQ_CFG_JSON_8: Persistent Configuration Storage
 */

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

// =============================================================================
// CONFIGURATION LIFECYCLE (REQ_CFG_JSON_12)
// =============================================================================

/**
 * @brief Initialize configuration manager
 * 
 * Opens NVS namespace "config". If namespace is empty or uninitialized,
 * calls config_factory_reset() to write default values from JSON schema.
 * 
 * Must be called once during system startup, before any other config_*
 * functions are used.
 * 
 * @return ESP_OK on success
 * @return ESP_ERR_NVS_* on NVS initialization failure
 * 
 * @note Not thread-safe. Call once during startup before multi-task access.
 * @note Subsequent calls will return ESP_ERR_INVALID_STATE.
 * 
 * @requirement REQ_CFG_JSON_12 AC-1
 */
esp_err_t config_init(void);

/**
 * @brief Reset all configuration to factory defaults
 * 
 * Erases all values in NVS "config" namespace and calls
 * config_write_factory_defaults() (auto-generated from JSON schema).
 * 
 * @return ESP_OK on success
 * @return ESP_ERR_NVS_* on NVS operation failure
 * 
 * @note Not thread-safe. Caller must ensure no concurrent NVS access.
 * @note All configuration values will be overwritten with defaults.
 * 
 * @requirement REQ_CFG_JSON_9
 */
esp_err_t config_factory_reset(void);

/**
 * @brief Manually commit pending NVS changes
 * 
 * Commits all pending NVS write operations to flash storage.
 * Use this after multiple _no_commit() calls to batch writes.
 * 
 * @return ESP_OK on success
 * @return ESP_ERR_NVS_* on commit failure
 * 
 * @note Thread-safe. NVS internal locking ensures safe concurrent access.
 * 
 * @requirement REQ_CFG_JSON_8
 */
esp_err_t config_commit(void);

/**
 * @brief Write factory defaults to NVS (auto-generated)
 * 
 * This function is generated by tools/generate_config_factory.py from
 * config_schema.json during build. It writes all default values to NVS.
 * 
 * Do not call directly - use config_factory_reset() instead.
 * 
 * @requirement REQ_CFG_JSON_4
 */
void config_write_factory_defaults(void);

// =============================================================================
// STRING PARAMETER ACCESS (REQ_CFG_JSON_7)
// =============================================================================

/**
 * @brief Get string parameter value
 * 
 * Reads string directly from NVS using provided key.
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[out] buffer Buffer to store string (must be at least buf_len bytes)
 * @param[in] buf_len Maximum buffer size (including null terminator)
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key or buffer is NULL
 * @return ESP_ERR_NVS_NOT_FOUND if key doesn't exist in NVS
 * @return ESP_ERR_NVS_INVALID_LENGTH if buffer too small
 * 
 * @note Thread-safe. NVS internal locking ensures safe concurrent access.
 * 
 * @requirement REQ_CFG_JSON_7 AC-1
 */
esp_err_t config_get_string(const char* key, char* buffer, size_t buf_len);

/**
 * @brief Set string parameter value
 * 
 * Writes string directly to NVS using provided key.
 * No validation performed (browser validates using JSON schema).
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[in] value New parameter value (null-terminated string)
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key or value is NULL
 * @return ESP_ERR_NVS_* on NVS write failure
 * 
 * @note Thread-safe. NVS internal locking ensures safe concurrent access.
 * 
 * @requirement REQ_CFG_JSON_7 AC-2
 */
esp_err_t config_set_string(const char* key, const char* value);

/**
 * @brief Set string parameter without committing to flash
 * 
 * Writes string to NVS but does NOT commit.
 * Use config_commit() after batch updates for better performance.
 * 
 * @param[in] key NVS key name
 * @param[in] value New parameter value (null-terminated string)
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key or value is NULL
 * @return ESP_ERR_NVS_* on NVS write failure
 * 
 * @note Thread-safe. NVS internal locking ensures safe concurrent access.
 * 
 * @requirement REQ_CFG_JSON_7 AC-2
 */
esp_err_t config_set_string_no_commit(const char* key, const char* value);

// =============================================================================
// INTEGER PARAMETER ACCESS (REQ_CFG_JSON_7)
// =============================================================================

/**
 * @brief Get int32 parameter value
 * 
 * Reads 32-bit signed integer directly from NVS using provided key.
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[out] value Pointer to store parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key or value is NULL
 * @return ESP_ERR_NVS_NOT_FOUND if key doesn't exist in NVS
 * 
 * @requirement REQ_CFG_JSON_7 AC-1
 */
esp_err_t config_get_int32(const char* key, int32_t* value);

/**
 * @brief Set int32 parameter value
 * 
 * Writes 32-bit signed integer directly to NVS using provided key.
 * No validation performed (browser validates using JSON schema).
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[in] value New parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key is NULL
 * @return ESP_ERR_NVS_* on NVS write failure
 * 
 * @requirement REQ_CFG_JSON_7 AC-2
 */
esp_err_t config_set_int32(const char* key, int32_t value);

/**
 * @brief Get int16 parameter value
 * 
 * Reads 16-bit signed integer directly from NVS using provided key.
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[out] value Pointer to store parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key or value is NULL
 * @return ESP_ERR_NVS_NOT_FOUND if key doesn't exist in NVS
 * 
 * @requirement REQ_CFG_JSON_7 AC-1
 */
esp_err_t config_get_int16(const char* key, int16_t* value);

/**
 * @brief Set int16 parameter value
 * 
 * Writes 16-bit signed integer directly to NVS using provided key.
 * No validation performed (browser validates using JSON schema).
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[in] value New parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key is NULL
 * @return ESP_ERR_NVS_* on NVS write failure
 * 
 * @requirement REQ_CFG_JSON_7 AC-2
 */
esp_err_t config_set_int16(const char* key, int16_t value);

/**
 * @brief Set int16 parameter without committing to flash
 * 
 * Writes int16 to NVS but does NOT commit.
 * Use config_commit() after batch updates for better performance.
 * 
 * @param[in] key NVS key name
 * @param[in] value New parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key is NULL
 * @return ESP_ERR_NVS_* on NVS write failure
 * 
 * @note Thread-safe. NVS internal locking ensures safe concurrent access.
 * 
 * @requirement REQ_CFG_JSON_7 AC-2
 */
esp_err_t config_set_int16_no_commit(const char* key, int16_t value);

// =============================================================================
// BOOLEAN PARAMETER ACCESS (REQ_CFG_JSON_7)
// =============================================================================

/**
 * @brief Get boolean parameter value
 * 
 * Reads boolean (stored as uint8) directly from NVS using provided key.
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[out] value Pointer to store parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key or value is NULL
 * @return ESP_ERR_NVS_NOT_FOUND if key doesn't exist in NVS
 * 
 * @requirement REQ_CFG_JSON_7 AC-1
 */
esp_err_t config_get_bool(const char* key, bool* value);

/**
 * @brief Set boolean parameter value without commit
 * 
 * Writes boolean to NVS but does NOT commit.
 * Use config_commit() after batch updates for better performance.
 * 
 * @param[in] key NVS key name
 * @param[in] value New parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key is NULL
 * @return ESP_ERR_NVS_* on NVS write failure
 * 
 * @note Thread-safe. NVS internal locking ensures safe concurrent access.
 * 
 * @requirement REQ_CFG_JSON_7 AC-2
 */
esp_err_t config_set_bool_no_commit(const char* key, bool value);

/**
 * @brief Set boolean parameter value
 * 
 * Writes boolean (stored as uint8) directly to NVS using provided key.
 * No validation performed (browser validates using JSON schema).
 * 
 * @param[in] key NVS key name (must match config_schema.json field key)
 * @param[in] value New parameter value
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG if key is NULL
 * @return ESP_ERR_NVS_* on NVS write failure
 * 
 * @requirement REQ_CFG_JSON_7 AC-2
 */
esp_err_t config_set_bool(const char* key, bool value);

// =============================================================================
// BULK JSON CONFIGURATION API (REQ_CFG_JSON_12, REQ_CFG_JSON_13)
// =============================================================================

/**
 * @brief Get embedded JSON schema for dynamic UI generation
 * 
 * Returns pointer to embedded config_schema.json string.
 * Schema is embedded at build time via EMBED_FILES in CMakeLists.txt.
 * 
 * @param[out] schema_json Pointer to embedded schema string (no free() needed)
 * @return ESP_OK on success
 * @return ESP_ERR_NOT_FOUND if schema not embedded
 * @return ESP_ERR_INVALID_ARG if schema_json is NULL
 * 
 * @requirement REQ_CFG_JSON_12 AC-1
 */
esp_err_t config_get_schema_json(char **schema_json);

/**
 * @brief Read all configuration values as structured JSON array
 * 
 * Reads JSON schema to enumerate all defined fields, then calls appropriate
 * config_get_xxx() function for each field based on schema type.
 * Builds JSON array with {key, type, value} objects.
 * 
 * Example output:
 * [
 *   {"key":"wifi_ssid","type":"string","value":"MyNetwork"},
 *   {"key":"led_count","type":"integer","value":50}
 * ]
 * 
 * @param[out] config_json Allocated JSON string (caller must free())
 * @return ESP_OK on success
 * @return ESP_ERR_NO_MEM on allocation failure
 * @return ESP_ERR_INVALID_ARG if config_json is NULL
 * 
 * @requirement REQ_CFG_JSON_12 AC-2
 */
esp_err_t config_get_all_as_json(char **config_json);

/**
 * @brief Update configuration from structured JSON array
 * 
 * Parses JSON array with {key, type, value} objects, validates field names
 * and types against schema, calls appropriate config_set_xxx_no_commit()
 * function for each field, then performs single config_commit().
 * 
 * Atomic operation: all fields update or none (rollback on error).
 * Unknown keys are ignored for forward compatibility.
 * 
 * Example input:
 * [
 *   {"key":"wifi_ssid","type":"string","value":"NewNetwork"},
 *   {"key":"led_count","type":"integer","value":100}
 * ]
 * 
 * @param[in] config_json JSON array string with key-type-value objects
 * @return ESP_OK on success
 * @return ESP_ERR_INVALID_ARG on validation failure or malformed JSON
 * @return ESP_ERR_NO_MEM on memory allocation failure
 * @return ESP_ERR_NVS_* on NVS operation failure
 * 
 * @requirement REQ_CFG_JSON_13 AC-1
 */
esp_err_t config_set_all_from_json(const char *config_json);

#ifdef __cplusplus
}
#endif
