# OpenFastTrack Configuration

# Project settings
project.name = ESP32 Distance Sensor
project.version = 1.0

# Input directories
input.directories = docs/requirements, docs/design, docs/test, main, components

# Requirements specification  
spec.item.name.singular = requirement
spec.item.name.plural = requirements
spec.item.artifact.types = req

# Design specification
design.item.name.singular = design
design.item.name.plural = designs  
design.item.artifact.types = dsn

# Implementation tracking
impl.item.name.singular = implementation
impl.item.name.plural = implementations
impl.item.artifact.types = impl

# Test specification
test.item.name.singular = test
test.item.name.plural = tests
test.item.artifact.types = tst

# Coverage requirements
coverage.req.to.dsn = 100%
coverage.dsn.to.impl = 100%
coverage.req.to.tst = 100%

# Validation rules
validate.requirements.format = true
validate.traceability.links = true
validate.duplicate.ids = true

# Output formats
output.html = true
output.markdown = true
output.coverage.reports = true

# Traceability matrix
traceability.matrix.format = html
