name: Build and deploy MkDocs site to gh-pages

on:
  push:
    branches:
      - main
  # Allow manual runs from the Actions UI for testing and one-off deploys
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings

      # Optional: run code/requirements/design generators here and write output into docs/
      # - name: Generate API/requirements/docs
      #   run: |
      #     python tools/generate_docs.py --out docs/api

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
