name: Build and deploy Sphinx documentation to gh-pages

on:
  push:
    branches:
      - main
      - feature/sphinx-needs-documentation
  # Allow manual runs from the Actions UI for testing and one-off deploys
  workflow_dispatch: {}

# Required permissions for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen graphviz
          version: 1.0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            "sphinx>=8.0" \
            "sphinx-needs>=6.0" \
            "sphinx-rtd-theme>=3.0" \
            "furo>=2025.0" \
            "myst-parser>=4.0" \
            "sphinxcontrib-plantuml>=0.31" \
            "breathe>=4.35"

      - name: Build Sphinx documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages

